export const CONTACTS_FETCHING = 'CONTACTS_FETCHING';
export const CONTACTS_FAVE = 'CONTACTS_FAVE';
export const CONTACTS_FAVED = 'CONTACTS_FAVED';
export const CONTACTS_UNFAVE = 'CONTACTS_UNFAVE'
export const CONTACTS_UNFAVED = 'CONTACTS_UNFAVED';
export const CONTACTS_RECEIVED = 'CONTACTS_RECEIVED';
export const CONTACT_ADDING = 'CONTACT_ADDING';
export const CONTACT_ADDED = 'CONTACT_ADDED';
export const CONTACT_REMOVING = 'CONTACT_REMOVING';
export const CONTACT_REMOVED = 'CONTACT_REMOVED';
export const CONTACT_REMOVE_BTN_SHOW = 'CONTACT_REMOVE_BTN_SHOW';
export const CONTACT_REMOVE_BTN_HIDE = 'CONTACT_REMOVE_BTN_HIDE'
export const CONTACTS_STATE = 'CONTACTS_STATE';
export const CONTACTS_CACHE = 'CONTACTS_CACHE';
export const CONTACTS_RESET = 'CONTACTS_RESET';

