export const CONTACTS_FETCHING = 'CONTACTS_FETCHING';
export const CONTACTS_RECEIVED = 'CONTACTS_RECEIVED';
export const CONTACT_FAVE = 'CONTACTS_FAVE';
export const CONTACT_FAVED = 'CONTACTS_FAVED';
export const CONTACT_UNFAVE = 'CONTACTS_UNFAVE';
export const CONTACT_UNFAVED = 'CONTACTS_UNFAVED';
export const CONTACT_ADDING = 'CONTACT_ADDING';
export const CONTACT_ADDED = 'CONTACT_ADDED';
export const CONTACT_REMOVING = 'CONTACT_REMOVING';
export const CONTACT_REMOVED = 'CONTACT_REMOVED';
export const CONTACTS_STATE = 'CONTACTS_STATE';
export const CONTACTS_CACHE = 'CONTACTS_CACHE';

